development:
  stripe:
    publishable_key: pk_test_6hbvZlSXkHolRU1ESYDqfJrC00Y4Klt0u0
    secret_key: ENV['DEV_SECRET_KEY']

test: &development

production:
  stripe:
    publishable_key: pk_test_6hbvZlSXkHolRU1ESYDqfJrC00Y4Klt0u0
    secret_key: ENV['SECRET_KEY']
