development:
  stripe:
    publishable_key: pk_test_6hbvZlSXkHolRU1ESYDqfJrC00Y4Klt0u0
    secret_key: sk_test_MKb6z65TEkrxeICUAB3s0Hll003LiYiy2l

test: &development

production:
  stripe:
    publishable_key: pk_test_6hbvZlSXkHolRU1ESYDqfJrC00Y4Klt0u0
    secret_key: sk_test_MKb6z65TEkrxeICUAB3s0Hll003LiYiy2l
